<?php

namespace Core\helper;

class CleanUrl
{

    private string|null $url;

    public function clearUrl(string|null $url): string
    {

        $this->url = $url;

        // Array de caracteres não aceitos
        $unaccepted_characters = [
            'À',
            'Á',
            'Â',
            'Ã',
            'Ä',
            'Å',
            'Æ',
            'Ç',
            'È',
            'É',
            'Ê',
            'Ë',
            'Ì',
            'Í',
            'Î',
            'Ï',
            'Ð',
            'Ñ',
            'Ò',
            'Ó',
            'Ô',
            'Õ',
            'Ö',
            'Ø',
            'Ù',
            'Ú',
            'Û',
            'Ü',
            'ü',
            'Ý',
            'Þ',
            'ß',
            'à',
            'á',
            'â',
            'ã',
            'ä',
            'å',
            'æ',
            'ç',
            'è',
            'é',
            'ê',
            'ë',
            'ì',
            'í',
            'î',
            'ï',
            'ð',
            'ñ',
            'ò',
            'ó',
            'ô',
            'õ',
            'ö',
            'ø',
            'ù',
            'ú',
            'û',
            'ý',
            'ý',
            'þ',
            'ÿ',
            '"',
            "'",
            '!',
            '@',
            '#',
            '$',
            '%',
            '&',
            '*',
            '(',
            ')',
            '_',
            '+',
            '=',
            '{',
            '[',
            '}',
            ']',
            '?',
            ';',
            ':',
            '.',
            ',',
            '\\',
            '\'',
            '<',
            '>',
            '°',
            'º',
            'ª',
            ' '
        ];

        // Array de caracteres aceitos
        $accepted_characters = [
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'c',
            'e',
            'e',
            'e',
            'e',
            'i',
            'i',
            'i',
            'i',
            'd',
            'n',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'u',
            'u',
            'u',
            'u',
            'u',
            'y',
            'b',
            's',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'c',
            'e',
            'e',
            'e',
            'e',
            'i',
            'i',
            'i',
            'i',
            'd',
            'n',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'u',
            'u',
            'u',
            'y',
            'y',
            'y',
            'y',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            ''
        ];

        // Substituir os caracteres não aceitos pelos caraters aceitos

        $this->url = str_replace(mb_convert_encoding($unaccepted_characters, 'ISO-8859-1', 'UTF-8'), $accepted_characters, mb_convert_encoding(strip_tags(trim(rtrim($this->url, "/"))), 'ISO-8859-1', 'UTF-8'));

        return $this->url;
    }
}